# -*- coding: utf-8 -*-
"""Fine_Tuning Llama.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15PpO5ECyvapPEoSr9ujmD5DredVc-vKg
"""

pip install -U cuda-bindings==12.9.6

!pip install -q unsloth trl

from unsloth import FastLanguageModel # fastlanguagemodel is a loader that can load the model qiuckly and fast
import torch

max_seq_length = 2048 # len of token from model at once
dtype = None
load_in_4bit = True

"""3B parameters × 4 bits
= 12 billion bits
12 billion bits ÷ 8
= 1.5 billion bytes
≈ 1.5 GB

Llama-3.2-3B
FP32 ≈ 12 GB
FP16 ≈ 6 GB
4-bit ≈ 1.5 GB
"""

max_seq_length = 2048 # Choose any! Unsloth also supports RoPE (Rotary Positinal Embedding) scaling internally.
dtype = None # None for auto detection. Float16 for Tesla T4, V100, Bfloat16 for Ampere+
load_in_4bit = True # Use 4bit quantization to reduce memory usage. Can be False.

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "unsloth/Llama-3.2-3B-Instruct", # or choose "unsloth/Llama-3.2-1B-Instruct"
    max_seq_length = max_seq_length,
    dtype = dtype,
    load_in_4bit = load_in_4bit, # Will load the 4Bit Quantized Model
)

"""R bada
=
More learning
More VRAM

r chhota
=
Less learning
Less VRAM

Original matrix:

4096 × 4096

bahut bada hai.

LoRA bolta hai:

Main itna bada matrix train nahi karunga.

Main chhota representation use karunga.

4096 × 16
16 × 4096

after this model will freeze
"""

model = FastLanguageModel.get_peft_model( # Do not train this model we initiize one adapdter here in that adapter we have our trained data  LoRA
    model,
    r = 16,
    target_modules = ["q_proj","k_proj","v_proj","o_proj", # Changed target_module to target_modules and added a comma
                    "gate_proj","up_proj","down_proj"], #p matlab projection layer  q-query,k-key,v-value,o-final output,gate- model decite which info where,up-if data expand,-down-data compress krna
    lora_alpha = 16, #  alpha = scaling factor Low-Rank Adaptation.Ye ek technique hai jisse hum poore LLM ko train nahi karte, sirf kuch chhote matrices karte hain.
    lora_dropout=0,  #  Dropout matlab training ke time:  Kuch connections temporarily band  overfitting kam
    bias = "none",    #
    use_gradient_checkpointing = "unsloth",
    random_state = 3407,
    use_rslora = False,
    loftq_config = None,
)

from datasets import load_dataset

dataset = load_dataset(
    "ServiceNow-AI/R1-Distill-SFT", #hugung face library
    "v0",
    split = "train"
)

dataset[:2]

r1_prompt = """You are a reflective assistant engaging in thorough, iterative reasoning, mimicking human stream-of-consciousness thinking. Your approach emphasizes exploration, self-doubt, and continuous refinement before coming up with an answer.
<problem>
{}
</problem>

{}
{}
"""
EOS_TOKEN = tokenizer.eos_token

def formatting_prompts_func(examples):
  problems = examples["problem"]
  thoughts = examples["reannotated_assistant_content"]
  solutions = examples["solution"]
  texts = []

  for problem, thought, solution in zip(problems, thoughts, solutions):
    text = r1_prompt.format(problem, thought, solution)+EOS_TOKEN
    texts.append(text)

  return {"text": texts}

dataset = dataset.map(formatting_prompts_func, batched = True,)

import warnings
warnings.filterwarnings("ignore")
!pip install trl # Ensure trl is installed

from trl import SFTTrainer
from transformers import TrainingArguments, DataCollatorForSeq2Seq
from unsloth import is_bfloat16_supported

trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = dataset,
    dataset_text_field = "text",
    max_seq_length = max_seq_length,
    dataset_num_proc = 0, # Number of processors to use for processing the dataset
    packing = False, # Can make training 5x faster for short sequences.
    args = TrainingArguments(
        per_device_train_batch_size = 2, # The batch size per GPU/TPU core
        gradient_accumulation_steps = 4, # Number of steps to perform befor each gradient accumulation
        warmup_steps = 5, # Few updates with low learning rate before actual training
        max_steps = 60, # Specifies the total number of training steps (batches) to run.
        learning_rate = 2e-4,
        save_strategy="no",
        fp16 = not is_bfloat16_supported(),
        bf16 = is_bfloat16_supported(),
        logging_steps = 1,
        optim = "adamw_8bit", # Optimizer
        weight_decay = 0.01,
        lr_scheduler_type = "linear",
        seed = 3407,
        output_dir = "outputs",
        report_to = "none", # Use this for WandB etc for observability
    ),
)

trainer_stats = trainer.train()

from unsloth.chat_templates import get_chat_template
sys_prompt = """You are a reflective assistant engaging in thorough, iterative reasoning, mimicking human stream-of-consciousness thinking. Your approach emphasizes exploration, self-doubt, and continuous refinement before coming up with an answer.
<problem>
{}
</problem>
"""
message = sys_prompt.format("How many 'r's are present in 'strawberry'?")
tokenizer = get_chat_template(
    tokenizer,
    chat_template = "llama-3.1",
)
FastLanguageModel.for_inference(model) # Enable native 2x faster inference

messages = [
    {"role": "user", "content": message},
]
inputs = tokenizer.apply_chat_template(
    messages,
    tokenize = True,
    add_generation_prompt = True, # Must add for generation
    return_tensors = "pt",
).to("cuda")

outputs = model.generate(input_ids = inputs, max_new_tokens = 1024, use_cache = True,
                         temperature = 1.5, min_p = 0.1)
response = tokenizer.batch_decode(outputs)

print(response[0])

model.save_pretrained("chintan-001-3B")  # Local saving
tokenizer.save_pretrained("chintan-001-3B")

model.save_pretrained_gguf("chintan-001-3B-GGUF", tokenizer,)

